version: '3.8'

services:
  app:
    build: .
    ports:
      - "8104:5004"
    environment:
      - ConnectionStrings__DbContext=Host=ms-aula-postgres;Port=5432;Pooling=true;Database=site-fisica;User Id=postgres;Password=admin
    networks:
      - app-network

networks:
  app-network:
    external: true  # Usa a mesma rede do ms-aula