# version: '3.8'

# services:
#   app:
#     build: .
#     ports:
#       - "8104:5004" # Porta para acessar o aplicativo no host
#       #- "8101:5001" # Porta HTTPS no host para o container
#     depends_on:
#       - postgres
#     environment:
#       - ConnectionStrings__DbContext=Host=postgres;Port=5432;Pooling=true;Database=site-fisica;User Id=postgres;Password=admin
#     networks:
#       - default

#   postgres:
#     image: postgres:latest
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: admin
#       POSTGRES_DB: site-fisica
#     ports:
#       - "5433:5433"
#     networks:
#       - default

# networks:
#   default:
#     name: rede-compartilhada
#     external: true
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8104:5004"
    environment:
      - ConnectionStrings__DbContext=Host=ms-aula-postgres;Port=5432;Pooling=true;Database=site-fisica;User Id=postgres;Password=admin
    networks:
      - app-network

networks:
  app-network:
    external: true  # Usa a mesma rede do ms-aula